# Base image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the application code to the container
COPY . .

# Set the command to run the application
CMD ["python", "spot_orders.py"]